required-players: 2
countdown-seconds: 30
lobby-spawn:
  world: 'world'
  x: 12.5
  y: 109.5
  z: -15.5
  yaw: 180
  pitch: 0
arenas:
  0:
    world: 'world'
    y-respawn: 90
    spawns:
      blue:
        x: 23.5
        y: 100.5
        z: -15.5
        yaw: 90
        pitch: 0
      green:
        x: 12.5
        y: 100.5
        z: -26.5
        yaw: 0
        pitch: 0
      yellow:
        x: 1.5
        y: 100.5
        z: -15.5
        yaw: 0
        pitch: -90
      red:
        x: 12.5
        y: 100.5
        z: -4.5
        yaw: 180
        pitch: 0
    beds:
      blue:
        x: 22
        y: 100
        z: -15
        facing: west
      green:
        x: 12
        y: 100
        z: -25
        facing: south
      yellow:
        x: 2
        y: 100
        z: -15
        facing: east
      red:
        x: 12
        y: 100
        z: -5
        facing: north