name: Section_6
version: '${project.version}'
main: com.section._6.section_6.Section_6
api-version: 1.19
authors: [Lucas]
description: learning
commands:
  playsong:
  broadcast:
  anvil:
  fi:
  talk:
  menu:
  giverole:
depend: [WorldEdit, NoteBlockAPI]
