required-players: 2
countdown-seconds: 30
lobby-spawn:
  world: 'world'
  x: 4.5
  y: 92.5
  z: 2.5
  yaw: 180
  pitch: 0
arenas:
  0:
    world: 'world'
    x: 5.5
    y: 91.5
    z: -22.5
    yaw: 0
    pitch: 0
  1:
    world: 'world'
    x: 20.5
    y: 91.5
    z: -23.5
    yaw: 0
    pitch: 0